//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.05.06 at 07:27:35 PM BST 
//


package jk.frame.config.xsd;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the jk.frame.config.xsd package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Application_QNAME = new QName("", "application");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: jk.frame.config.xsd
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Mappings }
     * 
     */
    public Mappings createMappings() {
        return new Mappings();
    }

    /**
     * Create an instance of {@link GlobalProperties }
     * 
     */
    public GlobalProperties createGlobalProperties() {
        return new GlobalProperties();
    }

    /**
     * Create an instance of {@link ClassDefinitions }
     * 
     */
    public ClassDefinitions createClassDefinitions() {
        return new ClassDefinitions();
    }

    /**
     * Create an instance of {@link Properties }
     * 
     */
    public Properties createProperties() {
        return new Properties();
    }

    /**
     * Create an instance of {@link Property }
     * 
     */
    public Property createProperty() {
        return new Property();
    }

    /**
     * Create an instance of {@link HandlerMappings }
     * 
     */
    public HandlerMappings createHandlerMappings() {
        return new HandlerMappings();
    }

    /**
     * Create an instance of {@link Classes }
     * 
     */
    public Classes createClasses() {
        return new Classes();
    }

    /**
     * Create an instance of {@link ModuleMapping }
     * 
     */
    public ModuleMapping createModuleMapping() {
        return new ModuleMapping();
    }

    /**
     * Create an instance of {@link ApplicationConfig }
     * 
     */
    public ApplicationConfig createApplicationConfig() {
        return new ApplicationConfig();
    }

    /**
     * Create an instance of {@link ModuleProperties }
     * 
     */
    public ModuleProperties createModuleProperties() {
        return new ModuleProperties();
    }

    /**
     * Create an instance of {@link ClassDefinition }
     * 
     */
    public ClassDefinition createClassDefinition() {
        return new ClassDefinition();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ApplicationConfig }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "application")
    public JAXBElement<ApplicationConfig> createApplication(ApplicationConfig value) {
        return new JAXBElement<ApplicationConfig>(_Application_QNAME, ApplicationConfig.class, null, value);
    }

}
